baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

#THEME#
theme = ["m10c"]

#THEME MODULE#
#[module]
#  [[module.imports]]
#    path = "github.com/joeroe/risotto"
#    disable=false
