baseURL = 'https://recurseit.com/'
languageCode = 'en-us'
title = "RecurseIT"

#THEME#
#theme = ["m10c"]
theme = ["m10c-27-02-2024"]

#THEME MODULE#
#[module]
#  [[module.imports]]
#    path = "github.com/joeroe/risotto"
#    disable=false

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

[params]
  author = "David Penaloza"
  description = "Network engineer and architect, passionate about learning, collaborating, sharing and hugging, with an uncanny ability to over-speak."
  menu_item_separator = " - "
  avatar = "https://recurseit.com/avatar.jpg"
  [[params.social]]
    icon = "linkedin"
    name = "LinkedIn"
    url = "https://linkedin.com/in/davidsamuelps"
  [[params.social]]
    icon = "twitter"
    name = "davidsamuelps"
    url = "https://x.com/davidsamuelps"

  # Default theme
  #[params.style]
  #  darkestColor = "#242930"
  #  darkColor = "#353b43"
  #  lightColor = "#afbac4"
  #  lightestColor = "#ffffff"
  #  primaryColor = "#57cc8a"

  # Green theme
  #[params.style]
  #  darkestColor = "#315659"
  #  darkColor = "#253031"
  #  lightColor = "#96a879"
  #  lightestColor = "#fff"
  #  primaryColor = "#dad865"

  # Red theme
  #[params.style]
  #  darkestColor = "#d35050"
  #  darkColor = "#212121"
  #  lightColor = "#d6d6d6"
  #  lightestColor = "#d3d3d3"
  #  primaryColor = "#ffffff"

  # To change theme colors, add the following lines:
  #[params.style]
  #  darkestColor = "#d35050"
  #  darkColor = "#212121"
  #  lightColor = "#f5e3e0"
  #  lightestColor = "#f5f5f5"
  #  primaryColor = "#ffffff"

